ConstructionWarehouse_Web/Controllers/StatusController.cs
using AutoMapper;
using ConstructionWarehouse_Utility;
using ConstructionWarehouse_Web.Models;
using ConstructionWarehouse_Web.Models.Dto;
using ConstructionWarehouse_Web.Services;
using ConstructionWarehouse_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ConstructionWarehouse_Web.Controllers
{
    public class StatusController : Controller
    {
        private readonly IStatusService _statusService;
        private readonly IMapper _mapper;
        public StatusController(IStatusService statusService, IMapper mapper)
        {
            _statusService = statusService;
            _mapper = mapper;
        }

        [Authorize]
        public async Task<IActionResult> IndexStatus()
        {
            List<StatusDTO> list = new();

            var response = await _statusService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<StatusDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> CreateStatus()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Администратор")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateStatus(StatusCreateDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _statusService.CreateAsync<APIResponse>(model, HttpContext.Session.GetString(StaticDetails.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Статус успешно добавлен";
                    return RedirectToAction(nameof(IndexStatus));
                }
            }
            TempData["error"] = "Произошла ошибка";
            return View(model);
        }

        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> UpdateStatus(int statusId)
        {
            var response = await _statusService.GetAsync<APIResponse>(statusId, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null && response.IsSuccess)
            {
                StatusDTO model = JsonConvert.DeserializeObject<StatusDTO>(Convert.ToString(response.Result));
                return View(_mapper.Map<StatusUpdateDTO>(model));
            }

            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "Администратор")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateStatus(StatusUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                TempData["success"] = "Статус успешно обновлен";
                var response = await _statusService.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(StaticDetails.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexStatus));
                }
            }
            TempData["error"] = "Произошла ошибка";
            return View(model);
        }

        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> DeleteStatus(int statusId)
        {
            var response = await _statusService.GetAsync<APIResponse>(statusId, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null && response.IsSuccess)
            {
                StatusDTO model = JsonConvert.DeserializeObject<StatusDTO>(Convert.ToString(response.Result));
                return View(model);
            }

            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "Администратор")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteStatus(StatusDTO model)
        {
            var response = await _statusService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Статус успешно удален";
                return RedirectToAction(nameof(IndexStatus));
            }
            TempData["error"] = "Произошла ошибка";

            return View(model);
        }
    }
}

ConstructionWarehouse_Web/Views/Status/CreateStatus.cshtml
@model ConstructionWarehouse_Web.Models.Dto.StatusCreateDTO

<form asp-action="CreateStatus">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Новая категория</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="StatusName" class="control-label pt-2" style="font-size: 20px;">Наименование</label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="StatusName" class="from-control" rows="1" style="width: 350px"></textarea>
                <span asp-validation-for="StatusName" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexStatus" asp-controller="Status" class="btn-primary btn form-control">Назад</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Создать" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ConstructionWarehouse_Web/Views/Status/DeleteStatus.cshtml
@model ConstructionWarehouse_Web.Models.Dto.StatusDTO

<form asp-action="DeleteStatus">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Удаление</h1>
        <hr />

        <input hidden asp-for="Id" />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="StatusName" class="control-label pt-2" style="font-size: 20px;">Наименование</label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="StatusName" disabled class="from-control" rows="1" style="width: 350px"></textarea>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexStatus" asp-controller="Status" class="btn-primary btn form-control">Назад</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Удалить" class="btn btn-danger form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ConstructionWarehouse_Web/Views/Status/IndexStatus.cshtml
@model IEnumerable<ConstructionWarehouse_Web.Models.Dto.StatusDTO>
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Статусы</h1>
        </div>
        <div class="cool text-end pt-1">
            <a asp-controller="Status" asp-action="CreateStatus" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Добавить новый статус</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Наименование статуса
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.StatusName</td>
                    <td>
                        <a asp-controller="Status" asp-action="UpdateStatus" asp-route-statusId="@item.Id" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="Status" asp-action="DeleteStatus" asp-route-statusId="@item.Id" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

ConstructionWarehouse_Web/Views/Status/UpdateStatus.cshtml
@model ConstructionWarehouse_Web.Models.Dto.StatusUpdateDTO

<form asp-action="UpdateStatus">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Изменение</h1>
        <hr />

        <input hidden asp-for="Id" />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="StatusName" class="control-label pt-2" style="font-size: 20px;">Наименование</label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="StatusName" class="from-control" rows="1" style="width: 350px"></textarea>
                <span asp-validation-for="StatusName" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexStatus" asp-controller="Status" class="btn-primary btn form-control">Назад</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Обновить" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}