ConstructionWarehouse_Web/Controllers/OrderController.cs
using AutoMapper;
using ConstructionWarehouse_Utility;
using ConstructionWarehouse_Web.Models;
using ConstructionWarehouse_Web.Models.Dto;
using ConstructionWarehouse_Web.Models.VM;
using ConstructionWarehouse_Web.Services;
using ConstructionWarehouse_Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Reflection;
using PdfSharpCore;
using PdfSharpCore.Pdf;
using TheArtOfDev.HtmlRenderer.PdfSharp;
using System.Reflection.PortableExecutable;
using Microsoft.AspNetCore.Authorization;

namespace ConstructionWarehouse_Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IProductService _productService;
        private readonly IUserService _userService;
        private readonly IStatusService _statusService;
        private readonly IPremiseService _premiseService;
        private readonly IMapper _mapper;
        public OrderController(IOrderService orderService, IMapper mapper, IProductService productService, IUserService userService, IStatusService statusService, IPremiseService premiseService)
        {
            _orderService = orderService;
            _mapper = mapper;
            _productService = productService;
            _userService = userService;
            _statusService = statusService;
            _premiseService = premiseService;
        }

        [Authorize]
        public async Task<IActionResult> IndexOrder(string? search)
        {
            IEnumerable<OrderDTO> list;

            var response = await _orderService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null && response.IsSuccess)
            {
                if (!string.IsNullOrEmpty(search))
                {
                    list = JsonConvert.DeserializeObject<List<OrderDTO>>(Convert.ToString(response.Result));
                    list = list.Where(u => u.Product.ProductName.ToLower().Contains(search.ToLower()) ||
                    u.User.FullName.ToLower().Contains(search.ToLower()) || u.Premise.PremiseName.ToLower().Contains(search.ToLower())
                    || u.Status.StatusName.ToLower().Contains(search.ToLower()) || u.Phone.ToLower().Contains(search.ToLower()));
                }
                else
                {
                    list = JsonConvert.DeserializeObject<List<OrderDTO>>(Convert.ToString(response.Result));
                }
            }
            else
            {
                list = JsonConvert.DeserializeObject<List<OrderDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> CreateOrder()
        {
            OrderCreateVM orderVM = new();
            var responseOne = await _productService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseTwo = await _userService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseThree = await _premiseService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseFour = await _statusService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (responseOne != null && responseOne.IsSuccess)
            {
                orderVM.ProductList = JsonConvert.DeserializeObject<List<ProductDTO>>
                    (Convert.ToString(responseOne.Result)).Select(i => new SelectListItem
                    {
                        Text = i.ProductName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseTwo != null && responseTwo.IsSuccess)
            {
                orderVM.UserList = JsonConvert.DeserializeObject<List<UserDTO>>
                    (Convert.ToString(responseTwo.Result)).Select(i => new SelectListItem
                    {
                        Text = i.FullName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseThree != null && responseThree.IsSuccess)
            {
                orderVM.PremiseList = JsonConvert.DeserializeObject<List<PremiseDTO>>
                    (Convert.ToString(responseThree.Result)).Select(i => new SelectListItem
                    {
                        Text = i.PremiseName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseFour != null && responseFour.IsSuccess)
            {
                orderVM.StatusList = JsonConvert.DeserializeObject<List<StatusDTO>>
                    (Convert.ToString(responseFour.Result)).Select(i => new SelectListItem
                    {
                        Text = i.StatusName,
                        Value = i.Id.ToString(),
                    });
            }
            return View(orderVM);
        }

        [HttpPost]
        [Authorize(Roles = "Администратор")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrder(OrderCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _orderService.CreateAsync<APIResponse>(model.Order, HttpContext.Session.GetString(StaticDetails.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Заказ успешно добавлен";
                    return RedirectToAction(nameof(IndexOrder));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            var responseOne = await _productService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseTwo = await _userService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseThree = await _premiseService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseFour = await _statusService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (responseOne != null && responseOne.IsSuccess)
            {
                model.ProductList = JsonConvert.DeserializeObject<List<ProductDTO>>
                    (Convert.ToString(responseOne.Result)).Select(i => new SelectListItem
                    {
                        Text = i.ProductName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseTwo != null && responseTwo.IsSuccess)
            {
                model.UserList = JsonConvert.DeserializeObject<List<UserDTO>>
                    (Convert.ToString(responseTwo.Result)).Select(i => new SelectListItem
                    {
                        Text = i.FullName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseThree != null && responseThree.IsSuccess)
            {
                model.PremiseList = JsonConvert.DeserializeObject<List<PremiseDTO>>
                    (Convert.ToString(responseThree.Result)).Select(i => new SelectListItem
                    {
                        Text = i.PremiseName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseFour != null && responseFour.IsSuccess)
            {
                model.StatusList = JsonConvert.DeserializeObject<List<StatusDTO>>
                    (Convert.ToString(responseFour.Result)).Select(i => new SelectListItem
                    {
                        Text = i.StatusName,
                        Value = i.Id.ToString(),
                    });
            }
            TempData["error"] = "Произошла ошибка";
            return View(model);
        }

        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> UpdateOrder(int orderId)
        {
            OrderUpdateVM orderVM = new();
            var response = await _orderService.GetAsync<APIResponse>(orderId, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null && response.IsSuccess)
            {
                OrderDTO model = JsonConvert.DeserializeObject<OrderDTO>(Convert.ToString(response.Result));
                orderVM.Order = _mapper.Map<OrderUpdateDTO>(model);
            }

            var responseOne = await _productService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseTwo = await _userService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseThree = await _premiseService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseFour = await _statusService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (responseOne != null && responseOne.IsSuccess)
            {
                orderVM.ProductList = JsonConvert.DeserializeObject<List<ProductDTO>>
                    (Convert.ToString(responseOne.Result)).Select(i => new SelectListItem
                    {
                        Text = i.ProductName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseTwo != null && responseTwo.IsSuccess)
            {
                orderVM.UserList = JsonConvert.DeserializeObject<List<UserDTO>>

ConstructionWarehouse_Web/Views/Order/CreateOrder.cshtml
@model ConstructionWarehouse_Web.Models.VM.OrderCreateVM

<form asp-action="CreateOrder">
    <br/>
    <div class="container border p-3">
        <h1 class="text-primary">Заказ</h1>
        <hr/>

        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Order.ProductId" class="control-label pt-2" style="font-size: 20px;">Товар</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.ProductId" class="form-select" asp-items="@Model.ProductList" style="width: 250px">
                    <option disabled selected>--Выбрать товар--</option>
                </select>
                <span asp-validation-for="Order.ProductId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Order.Quantity" class="control-label pt-2" style="font-size: 20px;">Количество</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Order.Quantity" class="from-control" min="1" value="1"/>
                <span asp-validation-for="Order.Quantity" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Order.CustomerId" class="control-label pt-2" style="font-size: 20px;">Менеджер</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.CustomerId" class="form-select" asp-items="@Model.UserList" style="width: 250px">
                    <option disabled selected>--Выбрать менеджера--</option>
                </select>
                <span asp-validation-for="Order.CustomerId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Order.PremiseId" class="control-label pt-2" style="font-size: 20px;">Помещение</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.PremiseId" class="form-select" asp-items="@Model.PremiseList" style="width: 250px">
                    <option disabled selected>--Выбрать помещение--</option>
                </select>
                <span asp-validation-for="Order.PremiseId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Order.Phone" class="control-label pt-2" style="font-size: 20px;">Телефон</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Order.Phone" class="from-control" placeholder="+7 999 999 99 99..."/>
                <span asp-validation-for="Order.Phone" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Order.DeliveryStatusId" class="control-label pt-2" style="font-size: 20px;">Статус заказа</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.DeliveryStatusId" class="form-select" asp-items="@Model.StatusList" style="width: 250px">
                    <option disabled selected>--Выбрать статус--</option>
                </select>
                <span asp-validation-for="Order.DeliveryStatusId" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexOrder" asp-controller="Order" class="btn-primary btn form-control">Назад</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Оформить" class="btn btn-success form-control"/>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

ConstructionWarehouse_Web/Views/Order/DeleteOrder.cshtml
@model ConstructionWarehouse_Web.Models.VM.OrderDeleteVM

<form asp-action="DeleteOrder">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Удаление</h1>
        <hr />

        <input hidden asp-for="Order.Id"/>
        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Order.ProductId" class="control-label pt-2" style="font-size: 20px;">Товар</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.ProductId" disabled class="form-select" asp-items="@Model.ProductList" style="width: 250px">
                    <option disabled selected>--Выбрать товар--</option>
                </select>
            </div>

            <div class="col-2">
                <label asp-for="Order.Quantity" class="control-label pt-2" style="font-size: 20px;">Количество</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Order.Quantity" disabled class="from-control" min="1" />
            </div>

            <div class="col-2">
                <label asp-for="Order.CustomerId" class="control-label pt-2" style="font-size: 20px;">Менеджер</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.CustomerId" disabled class="form-select" asp-items="@Model.UserList" style="width: 250px">
                    <option disabled selected>--Выбрать менеджера--</option>
                </select>
            </div>

            <div class="col-2">
                <label asp-for="Order.PremiseId" class="control-label pt-2" style="font-size: 20px;">Помещение</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.PremiseId" disabled class="form-select" asp-items="@Model.PremiseList" style="width: 250px">
                    <option disabled selected>--Выбрать помещение--</option>
                </select>
            </div>

            <div class="col-2">
                <label asp-for="Order.Phone" class="control-label pt-2" style="font-size: 20px;">Телефон</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Order.Phone" disabled class="from-control" />
            </div>

            <div class="col-2">
                <label asp-for="Order.DeliveryStatusId" class="control-label pt-2" style="font-size: 20px;">Статус заказа</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.DeliveryStatusId" disabled class="form-select" asp-items="@Model.StatusList" style="width: 250px">
                    <option disabled selected>--Выбрать статус--</option>
                </select>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexOrder" asp-controller="Order" class="btn-primary btn form-control">Назад</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Удалить" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ConstructionWarehouse_Web/Views/Order/IndexOrder.cshtml
@model IEnumerable<ConstructionWarehouse_Web.Models.Dto.OrderDTO>
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Заказы</h1>
        </div>
        <div>
            <form method="get">
                <div class="form-inline form-group">
                    <input name="search" class="form-control" placeholder="Поиск" style="width: 350px" />
                    <br />
                    <input type="submit" value="Поиск/отмена" class="btn btn-success" />
                </div>
            </form>
        </div>
        <div class="cool text-end pt-1">
            <a asp-controller="Order" asp-action="CreateOrder" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Оформить заказ</a>
            <a asp-controller="Order" asp-action="GeneratedPDF" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Сформировать PDF</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Товар
                </th>
                <th>
                    Описание
                </th>
                <th>
                    Количество
                </th>
                <th>
                    Менеджер
                </th>
                <th>
                    Помещение
                </th>
                <th>
                    Телефон
                </th>
                <th>
                    Дата создания
                </th>
                <th>
                    Статус заказа
                </th>
                <th>
                    Цена
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Product.ProductName</td>
                    <td>@item.Product.Details</td>
                    <td>@item.Quantity</td>
                    <td>@item.User.FullName</td>
                    <td>@item.Premise.PremiseName</td>
                    <td>@item.Phone</td>
                    <td>@((item.OrderDate).ToString("dd.MM.yyyy"))</td>
                    <td>@item.Status.StatusName</td>
                    <td>@((item.Product.Price).ToString("c"))</td>
                    <td>
                        <a asp-controller="Order" asp-action="UpdateOrder" asp-route-orderId="@item.Id" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="Order" asp-action="DeleteOrder" asp-route-orderId="@item.Id" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>>

ConstructionWarehouse_Web/Views/Order/UpdateOrder.cshtml
@model ConstructionWarehouse_Web.Models.VM.OrderUpdateVM

<form asp-action="UpdateOrder">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Изменение</h1>
        <hr />

        <input hidden asp-for="Order.Id" />
        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Order.ProductId" class="control-label pt-2" style="font-size: 20px;">Товар</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.ProductId" class="form-select" asp-items="@Model.ProductList" style="width: 250px">
                    <option disabled selected>--Выбрать товар--</option>
                </select>
                <span asp-validation-for="Order.ProductId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Order.Quantity" class="control-label pt-2" style="font-size: 20px;">Количество</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Order.Quantity" class="from-control" min="1" />
                <span asp-validation-for="Order.Quantity" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Order.CustomerId" class="control-label pt-2" style="font-size: 20px;">Менеджер</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.CustomerId" class="form-select" asp-items="@Model.UserList" style="width: 250px">
                    <option disabled selected>--Выбрать менеджера--</option>
                </select>
                <span asp-validation-for="Order.CustomerId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Order.PremiseId" class="control-label pt-2" style="font-size: 20px;">Помещение</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.PremiseId" class="form-select" asp-items="@Model.PremiseList" style="width: 250px">
                    <option disabled selected>--Выбрать помещение--</option>
                </select>
                <span asp-validation-for="Order.PremiseId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Order.Phone" class="control-label pt-2" style="font-size: 20px;">Телефон</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Order.Phone" class="from-control" />
                <span asp-validation-for="Order.Phone" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Order.DeliveryStatusId" class="control-label pt-2" style="font-size: 20px;">Статус заказа</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Order.DeliveryStatusId" class="form-select" asp-items="@Model.StatusList" style="width: 250px">
                    <option disabled selected>--Выбрать статус--</option>
                </select>
                <span asp-validation-for="Order.DeliveryStatusId" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexOrder" asp-controller="Order" class="btn-primary btn form-control">Назад</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Обновить" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}