ConstructionWarehouse_Web/Controllers/InventoryController.cs
using AutoMapper;
using ConstructionWarehouse_Utility;
using ConstructionWarehouse_Web.Models;
using ConstructionWarehouse_Web.Models.Dto;
using ConstructionWarehouse_Web.Models.VM;
using ConstructionWarehouse_Web.Services;
using ConstructionWarehouse_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace ConstructionWarehouse_Web.Controllers
{
    public class InventoryController : Controller
    {
        private readonly IInventoryService _inventoryService;
        private readonly IProductService _productService;
        private readonly IPremiseService _premiseService;
        private readonly IMapper _mapper;
        public InventoryController(IInventoryService inventoryService, IMapper mapper, IProductService productService, IPremiseService premiseService)
        {
            _inventoryService = inventoryService;
            _mapper = mapper;
            _productService = productService;
            _premiseService = premiseService;
        }

        [Authorize]
        public async Task<IActionResult> IndexInventory(string? search)
        {
            IEnumerable<InventoryDTO> list;

            var response = await _inventoryService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null && response.IsSuccess)
            {
                if (!string.IsNullOrEmpty(search))
                {
                    list = JsonConvert.DeserializeObject<List<InventoryDTO>>(Convert.ToString(response.Result));
                    list = list.Where(u => u.Product.ProductName.ToLower().Contains(search.ToLower()) ||
                    u.Premise.PremiseName.ToLower().Contains(search.ToLower()));
                }
                else
                {
                    list = JsonConvert.DeserializeObject<List<InventoryDTO>>(Convert.ToString(response.Result));
                }
            }
            else
            {
                list = JsonConvert.DeserializeObject<List<InventoryDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> CreateInventory()
        {
            InventoryCreateVM inventoryVM = new();
            var responseOne = await _productService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseTwo = await _premiseService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (responseOne != null && responseOne.IsSuccess)
            {
                inventoryVM.ProductList = JsonConvert.DeserializeObject<List<ProductDTO>>
                    (Convert.ToString(responseOne.Result)).Select(i => new SelectListItem
                    {
                        Text = i.ProductName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseTwo != null && responseTwo.IsSuccess)
            {
                inventoryVM.PremiseList = JsonConvert.DeserializeObject<List<PremiseDTO>>
                    (Convert.ToString(responseTwo.Result)).Select(i => new SelectListItem
                    {
                        Text = i.PremiseName,
                        Value = i.Id.ToString(),
                    });
            }
            return View(inventoryVM);
        }

        [HttpPost]
        [Authorize(Roles = "Администратор")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateInventory(InventoryCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _inventoryService.CreateAsync<APIResponse>(model.Inventory, HttpContext.Session.GetString(StaticDetails.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Товар добавлен на склад";
                    return RedirectToAction(nameof(IndexInventory));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            var responseOne = await _productService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseTwo = await _premiseService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (responseOne != null && responseOne.IsSuccess)
            {
                model.ProductList = JsonConvert.DeserializeObject<List<ProductDTO>>
                    (Convert.ToString(responseOne.Result)).Select(i => new SelectListItem
                    {
                        Text = i.ProductName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseTwo != null && responseTwo.IsSuccess)
            {
                model.PremiseList = JsonConvert.DeserializeObject<List<PremiseDTO>>
                    (Convert.ToString(responseTwo.Result)).Select(i => new SelectListItem
                    {
                        Text = i.PremiseName,
                        Value = i.Id.ToString(),
                    });
            }
            TempData["error"] = "Произошла ошибка";
            return View(model);
        }

        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> UpdateInventory(int inventoryId)
        {
            InventoryUpdateVM inventoryVM = new();
            var response = await _inventoryService.GetAsync<APIResponse>(inventoryId, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null && response.IsSuccess)
            {
                InventoryDTO model = JsonConvert.DeserializeObject<InventoryDTO>(Convert.ToString(response.Result));
                inventoryVM.Inventory = _mapper.Map<InventoryUpdateDTO>(model);
            }

            var responseOne = await _productService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseTwo = await _premiseService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (responseOne != null && responseOne.IsSuccess)
            {
                inventoryVM.ProductList = JsonConvert.DeserializeObject<List<ProductDTO>>
                    (Convert.ToString(responseOne.Result)).Select(i => new SelectListItem
                    {
                        Text = i.ProductName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseTwo != null && responseTwo.IsSuccess)
            {
                inventoryVM.PremiseList = JsonConvert.DeserializeObject<List<PremiseDTO>>
                    (Convert.ToString(responseTwo.Result)).Select(i => new SelectListItem
                    {
                        Text = i.PremiseName,
                        Value = i.Id.ToString(),
                    });
                return View(inventoryVM);
            }

            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "Администратор")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateInventory(InventoryUpdateVM model)
        {
            if (ModelState.IsValid)
            {
                TempData["success"] = "Данные о товаре на складе были успешно обновлены";
                var response = await _inventoryService.UpdateAsync<APIResponse>(model.Inventory, HttpContext.Session.GetString(StaticDetails.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexInventory));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            var responseOne = await _productService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            var responseTwo = await _premiseService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (responseOne != null && responseOne.IsSuccess)
            {
                model.ProductList = JsonConvert.DeserializeObject<List<ProductDTO>>
                    (Convert.ToString(responseOne.Result)).Select(i => new SelectListItem
                    {
                        Text = i.ProductName,
                        Value = i.Id.ToString(),
                    });
            }
            if (responseTwo != null && responseTwo.IsSuccess)
            {
                model.PremiseList = JsonConvert.DeserializeObject<List<PremiseDTO>>
                    (Convert.ToString(responseTwo.Result)).Select(i => new SelectListItem
                    {
                        Text = i.PremiseName,
                        Value = i.Id.ToString(),
                    });
            }
            TempData["error"] = "Произошла ошибка";
            return View(model);
        }

        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> DeleteInventory(int inventoryId)
        {
            InventoryDeleteVM inventoryVM = new();
            var response = await _inventoryService.GetAsync<APIResponse>(inventoryId, HttpContext.Session.GetString(StaticDetails.SessionToken));
            if (response != null && response.IsSuccess)
            {

ConstructionWarehouse_Web/Views/Inventory/CreateInventory.cshtml
@model ConstructionWarehouse_Web.Models.VM.InventoryCreateVM

<form asp-action="CreateInventory">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Добавление товара на склад</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Inventory.ProductId" class="control-label pt-2" style="font-size: 20px;">Товар</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Inventory.ProductId" class="form-select" asp-items="@Model.ProductList" style="width: 250px">
                    <option disabled selected>--Выбрать товар--</option>
                </select>
                <span asp-validation-for="Inventory.ProductId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Inventory.Quantity" class="control-label pt-2" style="font-size: 20px;">Количество</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Inventory.Quantity" class="from-control" min="1" value="1" />
                <span asp-validation-for="Inventory.Quantity" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Inventory.PremiseId" class="control-label pt-2" style="font-size: 20px;">Помещение</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Inventory.PremiseId" class="form-select" asp-items="@Model.PremiseList" style="width: 250px">
                    <option disabled selected>--Выбрать помещение--</option>
                </select>
                <span asp-validation-for="Inventory.PremiseId" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexInventory" asp-controller="Inventory" class="btn-primary btn form-control">Назад</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Создать" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ConstructionWarehouse_Web/Views/Inventory/DeleteInventory.cshtml
@model ConstructionWarehouse_Web.Models.VM.InventoryDeleteVM

<form asp-action="DeleteInventory">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Удаление</h1>
        <hr />

        <input hidden asp-for="Inventory.Id" />
        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Inventory.ProductId" class="control-label pt-2" style="font-size: 20px;">Товар</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Inventory.ProductId" disabled class="form-select" asp-items="@Model.ProductList" style="width: 250px">
                    <option disabled selected>--Выбрать товар--</option>
                </select>
            </div>

            <div class="col-2">
                <label asp-for="Inventory.Quantity" class="control-label pt-2" style="font-size: 20px;">Количество</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Inventory.Quantity" disabled class="from-control" min="1" />
            </div>

            <div class="col-2">
                <label asp-for="Inventory.PremiseId" class="control-label pt-2" style="font-size: 20px;">Помещение</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Inventory.PremiseId" disabled class="form-select" asp-items="@Model.PremiseList" style="width: 250px">
                    <option disabled selected>--Выбрать помещение--</option>
                </select>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexInventory" asp-controller="Inventory" class="btn-primary btn form-control">Назад</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Удалить" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ConstructionWarehouse_Web/Views/Inventory/IndexInventory.cshtml
@model IEnumerable<ConstructionWarehouse_Web.Models.Dto.InventoryDTO>
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">На складе</h1>
        </div>
        <div>
            <form method="get">
                <div class="form-inline form-group">
                    <input name="search" class="form-control" placeholder="Поиск" style="width: 350px" />
                    <br />
                    <input type="submit" value="Поиск/отмена" class="btn btn-success" />
                </div>
            </form>
        </div>
        <div class="cool text-end pt-1">
            <a asp-controller="Inventory" asp-action="CreateInventory" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Добавить товар на склад</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Товар
                </th>
                <th>
                    Количество
                </th>
                <th>
                    Помещение
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Product.ProductName</td>
                    <td>@item.Quantity</td>
                    <td>@item.Premise.PremiseName</td>
                    <td>
                        <a asp-controller="Inventory" asp-action="UpdateInventory" asp-route-inventoryId="@item.Id" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="Inventory" asp-action="DeleteInventory" asp-route-inventoryId="@item.Id" class="btn btn-danger"><i class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>>

ConstructionWarehouse_Web/Views/Inventory/UpdateInventory.cshtml
@model ConstructionWarehouse_Web.Models.VM.InventoryUpdateVM

<form asp-action="UpdateInventory">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Изменение</h1>
        <hr />

        <input hidden asp-for="Inventory.Id" />
        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Inventory.ProductId" class="control-label pt-2" style="font-size: 20px;">Товар</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Inventory.ProductId" class="form-select" asp-items="@Model.ProductList" style="width: 250px">
                    <option disabled selected>--Выбрать товар--</option>
                </select>
                <span asp-validation-for="Inventory.ProductId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Inventory.Quantity" class="control-label pt-2" style="font-size: 20px;">Количество</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Inventory.Quantity" class="from-control" min="1" />
                <span asp-validation-for="Inventory.Quantity" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Inventory.PremiseId" class="control-label pt-2" style="font-size: 20px;">Помещение</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="Inventory.PremiseId" class="form-select" asp-items="@Model.PremiseList" style="width: 250px">
                    <option disabled selected>--Выбрать помещение--</option>
                </select>
                <span asp-validation-for="Inventory.PremiseId" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexInventory" asp-controller="Inventory" class="btn-primary btn form-control">Назад</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Обновить" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}